{"name": "test_case_add[add_002]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/接口case.xlsx'", "trace": "self = <scripts.test_departments.TestDepartment object at 0x0000024FCF435408>\ncase_id = 'add_002'\n\n    @pytest.mark.parametrize(\"case_id\", get_case_id(\"add\", 5))\n    def test_case_add(self, case_id):\n        # 1. 获取Excel表格中的数据\n>       em = base_excel.get_item_with_case_id(case_id)\n\ntest_departments.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\base\\base_excel.py:108: in get_item_with_case_id\n    return ExcelModule(case_id)\n..\\base\\base_excel.py:114: in __init__\n    row = get_rows_number_with_case_id(case_id)\n..\\base\\base_excel.py:89: in get_rows_number_with_case_id\n    cols_data = get_columns_value(\"B\")\n..\\base\\base_excel.py:67: in get_columns_value\n    columns_list_data = get_sheet_data()[key]\n..\\base\\base_excel.py:18: in get_sheet_data\n    sheet_name = load_excel().sheetnames\n..\\base\\base_excel.py:10: in load_excel\n    open_excel = openpyxl.load_workbook(excel_url)\nD:\\Python\\Python37\\lib\\site-packages\\openpyxl\\reader\\excel.py:316: in load_workbook\n    data_only, keep_links)\nD:\\Python\\Python37\\lib\\site-packages\\openpyxl\\reader\\excel.py:124: in __init__\n    self.archive = _validate_archive(fn)\nD:\\Python\\Python37\\lib\\site-packages\\openpyxl\\reader\\excel.py:96: in _validate_archive\n    archive = ZipFile(filename, 'r')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <zipfile.ZipFile [closed]>, file = './data/接口case.xlsx', mode = 'r'\ncompression = 0, allowZip64 = True, compresslevel = None\n\n    def __init__(self, file, mode=\"r\", compression=ZIP_STORED, allowZip64=True,\n                 compresslevel=None):\n        \"\"\"Open the ZIP file with mode read 'r', write 'w', exclusive create 'x',\n        or append 'a'.\"\"\"\n        if mode not in ('r', 'w', 'x', 'a'):\n            raise ValueError(\"ZipFile requires mode 'r', 'w', 'x', or 'a'\")\n    \n        _check_compression(compression)\n    \n        self._allowZip64 = allowZip64\n        self._didModify = False\n        self.debug = 0  # Level of printing: 0 through 3\n        self.NameToInfo = {}    # Find file info given name\n        self.filelist = []      # List of ZipInfo instances for archive\n        self.compression = compression  # Method of compression\n        self.compresslevel = compresslevel\n        self.mode = mode\n        self.pwd = None\n        self._comment = b''\n    \n        # Check if we were passed a file-like object\n        if isinstance(file, os.PathLike):\n            file = os.fspath(file)\n        if isinstance(file, str):\n            # No, it's a filename\n            self._filePassed = 0\n            self.filename = file\n            modeDict = {'r' : 'rb', 'w': 'w+b', 'x': 'x+b', 'a' : 'r+b',\n                        'r+b': 'w+b', 'w+b': 'wb', 'x+b': 'xb'}\n            filemode = modeDict[mode]\n            while True:\n                try:\n>                   self.fp = io.open(file, filemode)\nE                   FileNotFoundError: [Errno 2] No such file or directory: './data/接口case.xlsx'\n\nD:\\Python\\Python37\\lib\\zipfile.py:1207: FileNotFoundError"}, "parameters": [{"name": "case_id", "value": "'add_002'"}], "start": 1639492385192, "stop": 1639492385192, "uuid": "ad806d88-68bf-4bf0-be55-84d7e3cca13a", "historyId": "0f64d9265ba207395d65bf9df270b014", "testCaseId": "c0686b4e1f19ddaaee2bbf227515d6bf", "fullName": "scripts.test_departments.TestDepartment#test_case_add", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_departments"}, {"name": "subSuite", "value": "TestDepartment"}, {"name": "host", "value": "DESKTOP-LSEEA95"}, {"name": "thread", "value": "16392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_departments"}]}