{"name": "test_case_add[add_005]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test_departments.TestDepartment object at 0x11f19f748>, case_id = 'add_005'\n\n    @pytest.mark.parametrize(\"case_id\", get_case_id(\"add\", 5))\n    def test_case_add(self, case_id):\n        # 1. 获取Excel表格中的数据\n        em = base_excel.get_item_with_case_id(case_id)\n        # 2. 处理前置\n        self.deal_fixture(em)\n        # 3. 发送请求\n        res = requests.post(self.BASE_URL + em.url, data=em.data.encode('utf-8'), headers=eval(em.headers))\n        # 4. 断言\n>       assert_res(res, em)\n\nscripts/test_departments.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nres = <Response [200]>, em = <base.base_excel.ExcelModule object at 0x11f19f6a0>\n\n    def assert_res(res, em):\n    \n        # 如果这个断言是自己调用的，则不进行后续的断言操作\n        if os.getcwd() in traceback.extract_stack()[-3][0]:\n            return\n    \n        if em.expect_way == \"json\":\n>           assert res.json() == json.loads(em.expect_res)\nE           AssertionError\n\nbase/base_assert.py:12: AssertionError"}, "parameters": [{"name": "case_id", "value": "'add_005'"}], "start": 1576401936465, "stop": 1576401936535, "uuid": "bb78899f-8abc-4fac-9b6c-1cc8038c087a", "historyId": "cfcfba458ba86ff8c86d000854b14909", "testCaseId": "c0686b4e1f19ddaaee2bbf227515d6bf", "fullName": "scripts.test_departments.TestDepartment#test_case_add", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_departments"}, {"name": "subSuite", "value": "TestDepartment"}, {"name": "host", "value": "your-desired-host-name"}, {"name": "thread", "value": "31981-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_departments"}]}